<?php

use Application\Model\Register;

$title = 'Current Situation';
$this->headTitle($title);
?>
<div class="row">
    <h1><?= $this->escapeHtml($title) ?></h1>
    <div class="table-responsive-sm">
        <table class="table" id="situationTable">
            <thead class="thead-dark">
            <tr style="cursor:pointer">
                <th scope="col">Business</th>
                <th scope="col">Island</th>
                <th scope="col">Type</th>
                <th scope="col">Contact</th>
                <th scope="col">Reopening Date</th>
                <th scope="col">Condition</th>
                <th scope="col">Notice</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($businesses as $business) :
                /** @var $business Register */
            ?>
            <tr
            <?php
                $status = '';
                switch($business->getCondition()) {
                    case 'Fully operational':
                        $status = 'condition-green';
                        break;
                    case 'Partly operational':
                        $status = 'condition-yellow';
                        break;
                    case 'Not operational':
                        $status = 'condition-red';
                        break;
                }
                echo 'class="'.$status.'"';
            ?>
            >
                <td><?=$this->escapeHtml($business->getBusiness()) ?></td>
                <td><?=$this->escapeHtml($business->getLocation()) ?></td>
                <td><?=$this->escapeHtml($business->getType()) ?></td>
                <td>
                    <?=$this->escapeHtml($business->getContactperson()) ?><br />
                    <a href="tel:<?=$this->escapeHtml($business->getPhonenumber()) ?>"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span><?=$this->escapeHtml($business->getPhonenumber()) ?></a><br />
                    <a style="white-space: nowrap;" href="mailto:<?=$this->escapeHtml($business->getEmail()) ?>"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> E-Mail</a><br />
                    <?php if(!empty($business->getWebsite())): ?>
                        <a  style="white-space: nowrap;" href="<?=$business->getWebsite()?>" target="_blank">
                            <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                            Website
                        </a><br />
                    <?php endif; ?>
                    <?php
                    if($business->getGps()) {
                        echo '<a href="https://maps.google.com/?ll='.$business->getGps().'" target="_blank""><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span> Map</a>';
                    } else {
                        echo '<a href="https://maps.google.com/?q='.$business->getBusiness().'" target="_blank"><span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span> Map</a>';
                    }
                    ?>
                </td>
                <td><?=$this->escapeHtml($business->getStartdate()) ?></td>
                <td><?=$this->escapeHtml($business->getCondition()) ?></td>
                <td><?=$this->escapeHtml($business->getNotice()) ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#situationTable').DataTable({
                "lengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
            }
        );
    } );
</script>
