<?php

use Application\Model\Register;

$title = 'Current Situation';
$this->headTitle($title);
?>
<div class="row">
    <h1><?= $this->escapeHtml($title) ?></h1>
    <div class="table-responsive-sm">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Business</th>
                <th scope="col">Location</th>
                <th scope="col">Type</th>
                <th scope="col">Contactperson</th>
                <th scope="col">Phonenumber</th>
                <th scope="col">E-Mail</th>
                <th scope="col">Reopening Date</th>
                <th scope="col">Condition</th>
                <th scope="col">Website</th>
                <th scope="col">Coordinates</th>
                <th scope="col">Notice</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($businesses as $business) :
                /** @var $business Register */
            ?>
            <tr
            <?php
                $status = '';
                switch($business->getCondition()) {
                    case 'Fully operational':
                        $status = 'condition-green';
                        break;
                    case 'Partly operational':
                        $status = 'condition-yellow';
                        break;
                    case 'Not operational':
                        $status = 'condition-red';
                        break;
                }
                echo 'class="'.$status.'"';
            ?>
            >
                <td><?=$this->escapeHtml($business->getBusiness()) ?></td>
                <td><?=$this->escapeHtml($business->getLocation()) ?></td>
                <td><?=$this->escapeHtml($business->getType()) ?></td>
                <td><?=$this->escapeHtml($business->getContactperson()) ?></td>
                <td><?=$this->escapeHtml($business->getPhonenumber()) ?></td>
                <td><?=$this->escapeHtml($business->getEmail()) ?></td>
                <td><?=$this->escapeHtml($business->getStartdate()) ?></td>
                <td><?=$this->escapeHtml($business->getCondition()) ?></td>
                <td><?=$this->escapeHtml($business->getWebsite()) ?></td>
                <td><?=$this->escapeHtml($business->getGps()) ?></td>
                <td><?=$this->escapeHtml($business->getNotice()) ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
