<?php
$title = 'Login';
$this->headTitle($title);
?>
<div class="row">
<h1><?= $this->escapeHtml($title) ?></h1>

    <div class="col-md-6">
        <?php
        $form->setAttribute('action', $this->url('register', ['action' => 'authenticate']));

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag($form);

        ?>
    </div>
</div>
