<?php
$title = 'Register your business';
$this->headTitle($title);
?>
<div class="row">
<h1><?= $this->escapeHtml($title) ?></h1>
<p>* Mandatory Fields</p>

    <div class="col-md-6">
        <?php
        $form->setAttribute('action', $this->url('register', ['action' => 'index']));

        echo $this->form()->openTag($form);


        echo $this->formCollection($form);
        echo $this->form()->closeTag($form);

        ?>
    </div>
</div>
