<?php
$title = 'Update your business';
$this->headTitle($title);
?>
<div class="row">
<h1><?= $this->escapeHtml($title) ?></h1>
    <button type="button" class="btn btn-primary" onclick="location.href='/register/logout'">Logout</button>
<p>* Mandatory Fields</p>

    <div class="col-md-6">
        <?php
        $form->setAttribute('action', $this->url('register', ['action' => 'update']));

        echo $this->form()->openTag($form);


        echo $this->formCollection($form);
        echo $this->form()->closeTag($form);

        ?>
    </div>
</div>
