<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Gilistrong')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style_new.css'))
            ->prependStylesheet($this->basePath('css/datetime-polyfill.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/dataTables.bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('js/polyfiller.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo_new.png') ?>" height="28" alt="#Gili Strong"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php

                        $navigation = [
                            '/' => 'Home',
                            '/situation' => 'Current situation',
                            '/register' => 'Register your business',
                            '/register/update' => 'Update your business',
                        ];

                        foreach ($navigation as $key => $value) {
                            ?><li <?php
                            if (parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) === $key) {
                                echo 'class="active"';
                            }
                            ?>><a href="<?= $key ?>"><?= $value ?></a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">

            <?php
            $flash = $this->flashMessenger();
            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>


            <?= $this->content ?>
            <hr>
            <footer>
                <p>#GiliStrong - Overview of the condition of businesses on Gili Air, Gili Meno and Gili Trawangan</p>
                <p class="text-muted">For questions, please send email to <a href="mailto:info@freediveflow.com"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> info@freediveflow.com</a> and phone/wa <a href="tel:+628113981166"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> +62 811 3981166</a></p>
            </footer>
        </div>
        <script>
            webshim.polyfill('forms forms-ext');
        </script>
        <?= $this->inlineScript() ?>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-562923-9"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-562923-9');
        </script>
    </body>
</html>
