<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">#GiliStrong</span></h1>

    <p>
        Overview of the condition of businesses on Gili Air, Gili Meno, Gili Trawangan, Lombok and Bali
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Check current situation</h3>
            </div>
            <div class="panel-body">
                <p>
                    View the current condition of registered businesses
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('situation')?>"">Current Situation &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Register your business</h3>
            </div>
            <div class="panel-body">
                <p>
                    Register your business to provide information about the current condition
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('register')?>">Register &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Update your business</h3>
            </div>
            <div class="panel-body">
                <p>
                    Provide us with the latest condition updates of your business
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('register', ['controller' => 'register', 'action' => 'update'])?>">Update your business &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
