<div class="jumbotron">
    <h1>Welcome to <span class="brand-red">#GiliStrong</span></h1>

    <p>
        Overview of the condition of businesses on Gili Air, Gili Meno and Gili Trawangan
    </p>
    <small class="text-muted">
        GiliStrong is an online-platform to manage the situation on all three Gili Islands. Business and Property owners
        should register their properties in the registration form. If you have multiple businesses, please register
        multiple times with different e-mail addresses.</small><br />
    <small class="text-muted">
        In the first stage, his platform helps architects/officials to identify buildings, which need to be checked for
        structural soundness. As the process of rebuilding proceeds, owners should continuously update their status on
        the platform. In a later stage, this information can then be used for tourists to identify places that are open
        for business.<br />
	If someone would like to adapt this platform for Lombok, please contact us.
    </small>
    <h2>Map Overview</h2>
    <a href="/img/map/situation.jpg" target="_blank"> <img src="/img/map/situation.jpg" style="max-height:200px;" /></a>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Check current situation</h3>
            </div>
            <div class="panel-body">
                <p>
                    View the current condition of registered businesses
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('situation')?>"">Current Situation &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Register your business</h3>
            </div>
            <div class="panel-body">
                <p>
                    Register your business to provide information about the current condition
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('register')?>">Register &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Update your business</h3>
            </div>
            <div class="panel-body">
                <p>
                    Provide us with the latest condition updates of your business
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('register', ['controller' => 'register', 'action' => 'update'])?>">Update your business &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
