<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">#GiliStrong</span></h1>

    <p>
        Welcome Text goes here
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Check current situation</h3>
            </div>
            <div class="panel-body">
                <p>
                    Some description
                </p>

                <p><a class="btn btn-success pull-right" href="#">Current Situation &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Register your business</h3>
            </div>
            <div class="panel-body">
                <p>
                    Some description
                </p>

                <p><a class="btn btn-success pull-right" href="<?=$this->url('register')?>">Register &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">More options</h3>
            </div>
            <div class="panel-body">
                <p>
                    Edit your business, Contact Form..?
                </p>

                <p><a class="btn btn-success pull-right" href="#">More &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
